### ISSUE TITLE
AttributeError : with pycountry

### ISSUE THREAD

**Issue by noraj1337** [IceCTF/ColdCore#21]
Did someone already have this issue:

```
$ python3 app.py
Traceback (most recent call last):
  File "app.py", line 9, in <module>
    from utils import misc, select
  File "/home/shark/Dev/ColdCore/utils/select.py", line 24, in <module>
    Countries = [(country.alpha3, country.name) for country in pycountry.countries]
  File "/home/shark/Dev/ColdCore/utils/select.py", line 24, in <listcomp>
    Countries = [(country.alpha3, country.name) for country in pycountry.countries]
  File "/usr/lib/python3.6/site-packages/pycountry/db.py", line 22, in __getattr__
    raise AttributeError
AttributeError
```

`/usr/lib/python3.6/site-packages/pycountry/db.py`:

```python
[...]
    def __getattr__(self, key):
        if key not in self._fields:
            raise AttributeError
        return self._fields[key]
[...]
```

**Comment by jamiees2** [comment]
It seems like `alpha3` has changed to `alpha_3` in the latest version of pycountry.

**Comment by jamiees2** [comment]
This was fixed in a PR that I missed, so this has been fixed now :)

**Comment by noraj1337** [comment]
I confirm it's solved.
